//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAUM_ASP_tp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int Id { get; set; }
        public string num_cli { get; set; }
        public string nom_cli { get; set; }
        public string adress_cli { get; set; }
        public string ville_cli { get; set; }
    }
}
